// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18LlfwSh2HtsGVqEVbSa3GG_OEDRL8RM',
    appId: '1:350021275908:web:a349fce8f1a7215d0f0051',
    messagingSenderId: '350021275908',
    projectId: 'qatha-22c14',
    authDomain: 'qatha-22c14.firebaseapp.com',
    storageBucket: 'qatha-22c14.firebasestorage.app',
    measurementId: 'G-8N7T4P2SLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB5Wzjkq9vllmaH9u6EeQpAofB-HAdX5k',
    appId: '1:350021275908:android:098e368f45f361040f0051',
    messagingSenderId: '350021275908',
    projectId: 'qatha-22c14',
    storageBucket: 'qatha-22c14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt8uAgj7AJjn0hFrvs8mpJ3lNjkRMEGes',
    appId: '1:350021275908:ios:d4d2adf4afb2b77c0f0051',
    messagingSenderId: '350021275908',
    projectId: 'qatha-22c14',
    storageBucket: 'qatha-22c14.firebasestorage.app',
    iosClientId: '350021275908-u9538l7j6q5q6jrrmc2srgnom3mpjgup.apps.googleusercontent.com',
    iosBundleId: 'com.katha.kathaReader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt8uAgj7AJjn0hFrvs8mpJ3lNjkRMEGes',
    appId: '1:350021275908:ios:d4d2adf4afb2b77c0f0051',
    messagingSenderId: '350021275908',
    projectId: 'qatha-22c14',
    storageBucket: 'qatha-22c14.firebasestorage.app',
    iosClientId: '350021275908-u9538l7j6q5q6jrrmc2srgnom3mpjgup.apps.googleusercontent.com',
    iosBundleId: 'com.katha.kathaReader',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB18LlfwSh2HtsGVqEVbSa3GG_OEDRL8RM',
    appId: '1:350021275908:web:7a07186834c76b6a0f0051',
    messagingSenderId: '350021275908',
    projectId: 'qatha-22c14',
    authDomain: 'qatha-22c14.firebaseapp.com',
    storageBucket: 'qatha-22c14.firebasestorage.app',
    measurementId: 'G-7VRNJGFF2F',
  );
}
