name: katha_reader
description: Katha — Telugu stories. No ads. No coins.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  provider: ^6.1.2
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.3
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.0
  google_sign_in: ^6.2.1
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^9.2.2
  razorpay_flutter: ^1.4.5
  share_plus: ^10.1.4
  app_links: ^6.3.2
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true