/**
 * §7.1 Data access layer — thin Supabase wrappers (one place per concern).
 * UI components import via api.ts, not supabase.from(...) directly.
 */
export {
  sbGetDashboard,
  sbGetWallet,
  sbGetCreatorStories,
  sbCreateStory,
  sbUpdateStory,
  sbDeleteStory,
  sbGetStoryChapters,
  sbGetChapter,
  sbRenameChapter,
  sbDeleteChapter,
  sbDuplicateChapter,
  sbSaveDraft,
  sbPublishChapter,
  sbGetScheduledPublishes,
  sbScheduleChapter,
  sbRescheduleChapter,
  sbCancelScheduledPublish,
  sbGetAnalytics,
  sbGetModerationQueue,
  sbReviewModeration,
  sbGetMilestones,
  sbAcknowledgeMilestone,
  sbUploadImage,
  sbCheckHealth,
  sbRegisterDevice,
  sbListUserDevices,
  sbRemoveUserDevice,
  sbUpsertPhoneticCorrection,
  sbDeletePhoneticCorrection,
  sbLoadPhoneticCorrections,
  sbMigrateLocalPhoneticCorrections,
  sbTrackAnalyticsEvent,
} from '../lib/supabaseData';